project:
  type: website

website:
  title: "Bayesian Statistics Spring 2025"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: lectures.qmd
        text: Lectures
      - href: homeworks.qmd
        text: Homework
      - href: syllabus.qmd
        text: Syllabus

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: source




